name: be_fitness_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.6.0
  flutter_bloc: ^8.1.2
  sizer: ^2.0.15

  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0

  google_sign_in: ^6.0.2
  cloud_firestore: ^4.5.0
  firebase_storage: ^11.1.0
  flutter_native_splash: ^2.2.19
  equatable: ^2.0.5

  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3
  flutter_svg: ^2.0.4
  geolocator: ^9.0.2
  geocoding: ^2.1.0

  document_scanner_flutter: ^0.2.7
  responsive_framework: ^0.2.0
  image_picker: ^0.8.7+1
  cool_alert: ^2.0.1

  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3

  font_awesome_flutter: ^10.4.0

  gif_view: ^0.3.1
  dartz: ^0.10.1
  chat_bubbles: ^1.4.0

  flutter_rating_stars: ^1.0.3+4
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.5
  location: ^4.4.0
  loading_animation_widget: ^1.2.0+4
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  dio: ^5.1.1

  shared_preferences: ^2.1.0
  dynamic_color_theme: ^2.0.0
  dynamic_color: ^1.6.3

  google_fonts: ^4.0.4
  flutter_datetime_picker: ^1.5.1
  voice_message_package: ^1.0.41
  just_audio: ^0.9.32
  rating_summary: ^1.0.2+1
  syncfusion_flutter_sliders: ^20.4.54
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
    - assets/icons/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IntegralCF
      fonts:
        - asset: assets/fonts/integralCF/IntegralCF-Bold.otf
        - asset: assets/fonts/integralCF/IntegralCF-ExtraBold.otf
        - asset: assets/fonts/integralCF/IntegralCF-Medium.otf
        - asset: assets/fonts/integralCF/IntegralCF-Regular.otf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
