// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUZZw12B1dAT8NVxLKoDnNURiXztRcME',
    appId: '1:310094117223:web:da03ee769c7ef7a4f117c2',
    messagingSenderId: '310094117223',
    projectId: 'be-fitness-4ca28',
    authDomain: 'be-fitness-4ca28.firebaseapp.com',
    storageBucket: 'be-fitness-4ca28.appspot.com',
    measurementId: 'G-D1LPNQRZKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXVSV-kkTSiSCWbQjkIOXNGY8oGG7vy-I',
    appId: '1:310094117223:android:cc444535833bab3ef117c2',
    messagingSenderId: '310094117223',
    projectId: 'be-fitness-4ca28',
    storageBucket: 'be-fitness-4ca28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0yHlbDJvz2OrgJ2nyHvnE41GRmgpo31g',
    appId: '1:310094117223:ios:6c14a0303693b5d6f117c2',
    messagingSenderId: '310094117223',
    projectId: 'be-fitness-4ca28',
    storageBucket: 'be-fitness-4ca28.appspot.com',
    iosClientId: '310094117223-4kotoe8ggd0rg738fdpjrfr99fv3bvsp.apps.googleusercontent.com',
    iosBundleId: 'mehani.sim.beFitnessApp',
  );
}
